name: PR Preview Environments

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

  # workflow_dispatch:
  #   inputs:
  #     action:
  #       description: 'Action to perform'
  #       required: true
  #       default: 'deploy'
  #       type: choice
  #       options:
  #         - deploy
  #         - destroy

  #     env-name:
  #       description: 'Optional custom environment name (alphanumeric and dashes only)'
  #       required: false
  #       default: ''
  #       type: string

permissions:
  contents: read
  pull-requests: write

# concurrency:
#   group: preview-env-${{ github.event.ref || github.sha }}
#   cancel-in-progress: true

jobs:
  deploy-preview:
    # if: github.event.inputs.action == 'deploy'
    runs-on: ubuntu-latest
    # env:
    #   BRANCH_NAME: ${{ github.event.inputs.env-name}}
    #   COMMIT_SHA: ${{ github.sha }}
    #   VPS_HOST: ${{ secrets.VPS_HOST }}
    #   VPS_USER: ${{ secrets.VPS_USER }}
    #   SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkout backend repo
        uses: actions/checkout@v6
        with:
          repository: skaletek-io/simple-app-backend
          path: backend

      - name: Checkout frontend repo
        uses: actions/checkout@v6
        with:
          repository: skaletek-io/simple-app-frontend
          path: frontend
      - name: Verify file structure     
        run: |
          ls -la

          echo "==================== Backend repo files ===================="
          cd backend
          ls

          echo "==================== Frontend repo files ==================="
          cd ..
          cd frontend
          ls 


      # - name: Validate required secrets
      #   run: |
      #     test -n "$VPS_HOST"
      #     test -n "$VPS_USER"
      #     test -n "$SSH_PRIVATE_KEY"

      # - name: Compute environment metadata
      #   id: meta
      #   run: |
      #     ENV_NAME="$(./scripts/preview/env_name.sh "$BRANCH_NAME" "$PR_NUMBER")"
      #     echo "env_name=$ENV_NAME" >> "$GITHUB_OUTPUT"

      # - name: Setup SSH key
      #   run: |
      #     ./scripts/preview/setup_ssh.sh "$VPS_HOST" "$VPS_USER" "$SSH_PRIVATE_KEY"

      # - name: Sync repo to VPS
      #   run: |
      #     ssh preview-vps "mkdir -p ~/simple-app/previews/${{ steps.meta.outputs.env_name }}"
      #     rsync -az --delete \
      #       -e "ssh -F $HOME/.ssh/config" \
      #       --exclude '.git' \
      #       --exclude '.github' \
      #       --exclude 'frontend/node_modules' \
      #       ./ "preview-vps:~/simple-app/previews/${{ steps.meta.outputs.env_name }}/"
